from graph.state import InvestigationState

def generate_report(state: InvestigationState) -> InvestigationState:
    """
    Generate the final investigation report.
    """

    alert = state["alert"]
    mitre = state["mitre"]

    report = f"""
=====================================================================
               AI SECURITY INVESTIGATION REPORT
=====================================================================

Investigate ID : INV-{alert.agent_id}-{alert.timestamp[:10].replace("-", "")}
Generated By   : Wazuh AI Agent
AI Model       : Qwen3:8B

=====================================================================
ALERT INFORMATION
=====================================================================

Agent       : {alert.agent_name}
Alert Rule  : {alert.rule_description}
Severity    : {state["severity"].upper()}
Risk Level  : {state["risk"].upper()}
Timestamp   : {alert.timestamp}

=====================================================================
INVESTIGATION PLAN
=====================================================================

Goals Selected
--------------
✓ Collect Agent Context
✓ Collect Recent Activity
✓ MITRE ATT&CK Mapping

Reason
------
Need host context, recent activity patterns, and MITRE mapping
to assess potential privilege escalation risk.

=====================================================================
HOST INVESTIGATION
=====================================================================

{state["investigation"]}

=====================================================================
MITRE ATT&CK MAPPING
=====================================================================

Technique IDs
-------------
{chr(10).join(f" • {x}" for x in mitre["ids"])}

Techniques
----------
{chr(10).join(f" • {x}" for x in mitre["techniques"])}

Tactics
-------
{chr(10).join(f" • {x}" for x in mitre["tactics"])}

=====================================================================
AI SECURITY ANALYSIS
=====================================================================

{state["analysis"]}

=====================================================================
INVESTIGATION STATISTICS
=====================================================================

Evidence Sources Used : 2
Investigation Goals   : {len(state["plan"]["goals"])}
Related Alerts Found  : {len(state['recent_alerts'])}
MITRE Techniques      : {len(mitre['ids'])}
Risk Classification   : {state["risk"]}

=====================================================================
FINAL RECOMMENDATION
=====================================================================

Review this event and verify that the observed activity was expected.
If the action was not authorized, perform additional investigation
and initiate incident response procedures.

=====================================================================
            ✓ Investigation completed successfully
=====================================================================
"""
    state["report"] = report
    
    print("[✓] Report generated")

    return state