TOOLS = [
    {
    "name": " get_agent_info",
    "description": "Retreive the agent's status, OS, IP address and version."
    },
    {
        "name": "get_recent_alerts",
        "description": "Retrieve the last five alerts generated by the same agent."
    },
    {
        "name": "get_mitre",
        "description":"Retrieve MITRE ATT&CK tactics, techniques and IDs."
    }
]